languageCode = "en-us"
title = "datawookie"
theme = "wookie"
baseurl = "https://example.com"

# Limit number of entries in RSS feeds.
#
rssLimit = 20

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = ""
author = "Andrew B. Collier"
# logoimage = "images/logo.jpg"
# copyright = "foo"

[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Resume"
url = "/resume/"

[[menu.main]]
weight = 3
name = "Blog"
url = "/blog/"

[[menu.main]]
weight = 4
name = "Contact"
url = "/contact/"
