languageCode = "en-us"
title = "datawookie"
theme = "wookie"
baseurl = "https://example.com"

# Limit number of entries in RSS feeds.
#
rssLimit = 20

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = "A clean Hugo theme for websites"
# logoimage = "images/logo.jpg"
# copyright = "foo"

# mathjax = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
## Uncomment if you want mathjax enabled. The above cdn source is taken from https://gohugo.io/content-management/formats/#mathjax-with-hugo   

[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Features"
url = "/features/"
identifier = "features"
  [[menu.main]]
  parent = "features"
  weight = 1
  name = "Responsive design"
  url = "/features/responsive-design/"
  [[menu.main]]
  parent = "features"
  weight = 2
  name = "Nested menus"
  url = "/features/nested-menus/"
  identifier = "nested-menus"
    [[menu.main]]
    parent = "nested-menus"
    weight = 1
    name = "Third level page #1"
    url = "/features/nested-menus/third-level-1/"
    [[menu.main]]
    parent = "nested-menus"
    weight = 2
    name = "Third level page #2"
    url = "/features/nested-menus/third-level-2/"
    [[menu.main]]
    parent = "nested-menus"
    weight = 3
    name = "Third level page #3"
    url = "/features/nested-menus/third-level-3/"
  [[menu.main]]
  parent = "features"
  weight = 3
  name = "Two-column layout"
  url = "/features/two-column-layout/"
  [[menu.main]]
  parent = "features"
  weight = 4
  name = "Tags"
  url = "/features/tags/"

[[menu.main]]
weight = 3
name = "Resume"
url = "/resume/"

[[menu.main]]
weight = 4
name = "Blog"
url = "/blog/"

[[menu.main]]
weight = 5
name = "Contact"
url = "/contact/"
